---
title: "Hex Bathroom"
date: '2022-12-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
n_across <- 50

n_down <- 50

across_xs <- rep(c(0,0, sqrt(3)/4, sqrt(3)/2, sqrt(3)/2, sqrt(3)/4, 0), n_across) +
    rep(0:(n_across-1)*sqrt(3)/2, each = 7)

across_ys <- rep(c(0,.5, .75, .5, 0,-.25,0), n_across)

light_green <- c(
  # vertical diamonds
  seq(2551, 4901, n_down) + 2,
  seq(103, 2403, n_down*2),
  seq(103, 2403, n_down*2) + 1,
  seq(2599, 4949, n_down) - 2,
  seq(103, 2403, n_down*2) + 44,
  seq(103, 2403, n_down*2) + 45,
  seq(103, 103 + n_across - 6, 3),
  seq(104, 103 + n_across - 5, 3),
  seq(2551 + 5, 2551 + n_across - 5, 3),
  seq(2551 + 5 + n_across, 2551 + n_across - 5 + n_across, 3),
  seq(2403, 2403 + n_across - 6, 3),
  seq(2404, 2403 + n_across - 5, 3),
  seq(4851 + 5, 4851 + n_across - 5, 3),
  seq(4851 + 5 + n_across, 4851 + n_across - 5 + n_across, 3),
  # stars
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 103,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 103 + 500,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 103 + 1000,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 103 + 1500,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 123,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 123 + 500,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 123 + 1000,
  c(
      c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
      seq(362, by = 50, length.out = 2), 
      seq(362, by = 50, length.out = 2) + 1,
      c(2860,2861, 2863, 2864)
    ) + 123 + 1500
)

dark_green <- c(
  # outer every other dot
  seq(2501, 2549, 2), 
  seq(4951, 4999, 2),
  seq(2551, 4901, n_down),
  seq(2599, 4949, n_down),
  # inner every other dot
  seq(2651, 4801, n_down) + 4,
  seq(2699, 4849, n_down) - 4,
  seq(2655, 2695, 2),
  seq(4805, 4845, 2),
  # stars
  seq(2862 + 2*n_across + 3, by = 500, length.out = 4),
  seq(2862 + 2*n_across + 23, by = 500, length.out = 4)
)

hexagon = tibble(
  x = rep(across_xs, n_down),
  y = rep(across_ys, n_down) + 
    rep((0:(n_down - 1))*(1.5), each = 7*n_across),
  group = rep(1:(n_across*n_down), each = 7),
  colors = if_else(group %in% light_green,
                   "#8aa48f",
                   if_else(group %in% dark_green,
                          "#365447",
                          "white"))
)

hexagon2 <-
  hexagon %>% 
  mutate(x = x + sqrt(3)/4,
         y = y + .75,
         group = group + max(group),
  colors = if_else(group %in% light_green,
                   "#8aa48f",
                   if_else(group %in% dark_green,
                          "#365447",
                          "white"))
)

```

```{r, fig.width=10, fig.height=10}

# #8aa48f light
# #365447 dark
# #754a41 burgundy

hexagon %>% 
  ggplot(aes(x = x,
             y = y, 
             group = group)) +
  geom_polygon(color = "black",
               aes(fill = colors)) +
  geom_polygon(data = hexagon2,
               aes(fill = colors),
               color = "black") +
  # geom_text(data = . %>%
  #             group_by(group) %>%
  #             summarize(mid_x = mean(x),
  #                       mid_y = mean(y)),
  #           aes(x = mid_x,
  #               y = mid_y,
  #               label = group)) +
  # geom_text(data = hexagon2 %>%
  #             group_by(group) %>%
  #             summarize(mid_x = mean(x),
  #                       mid_y = mean(y)),
  #           aes(x = mid_x,
  #               y = mid_y,
  #               label = group)) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```

```{r}
ggsave(filename = "bathroom_floor.png")
ggsave(filename = "bathroom_floor.pdf")
```

