---
title: "Hex Bathroom"
date: '2022-12-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggforce)
```

Parameters

```{r}
shower_width <- 36

shower_length <- 72

n_across <- shower_width

n_down <- ceiling(shower_length/(3/sqrt(3)))

inset_left <- 5
inset_right <- 4
inset_top <- 6
inset_bottom <- 5

across_xs <- rep(c(0,0, .5, 1, 1, .5, 0), n_across) +
    rep(0:(n_across-1), each = 7)

across_ys <- rep(c(0, 1/sqrt(3), 3/(2*sqrt(3)), 1/sqrt(3), 0,-1/(2*sqrt(3)), 0), n_across)
```

Color locations

```{r}
light_green <- c(
  # vertical diamonds
  # left column, middle
  seq((inset_bottom + 1)*n_across + inset_left + 2, 
      2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 2, 
      2*n_across),
  # left column, left side
  seq((inset_bottom + 2)*n_across + inset_left + 1, 
      2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 1, 
      4*n_across),
  # left column, right side
  seq((inset_bottom + 2)*n_across + inset_left + 2, 
      2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 2, 
      4*n_across),
  # right column, middle
  seq((inset_bottom + 2)*n_across - inset_right - 1, 
      2*n_across*n_down - (inset_top + 1)*n_across - inset_right -1, 
      2*n_across),
  # right column, right side
  seq((inset_bottom + 3)*n_across - inset_right - 1, 
      2*n_across*n_down - (inset_top)*n_across - inset_right - 1, 
      4*n_across),
  # right column, left side
  seq((inset_bottom + 3)*n_across - inset_right - 2, 
      2*n_across*n_down - (inset_top)*n_across - inset_right - 2, 
      4*n_across),
  # bottom row, bottom
  seq((inset_bottom + 1)*n_across + inset_left + 2,
      (inset_bottom + 2)*n_across - inset_right - 1,
      3),
  # bottom row, top
  seq((inset_bottom + 3)*n_across + inset_left + 2,
      (inset_bottom + 4)*n_across - inset_right - 1,
      3),
  # bottom row, middle
  seq((inset_bottom + 2)*n_across + inset_left + 1,
      (inset_bottom + 3)*n_across - inset_right - 2,
      3),
  seq((inset_bottom + 2)*n_across + inset_left + 2,
      (inset_bottom + 3)*n_across - inset_right - 1,
      3),
  # top row, top
  seq(2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 2,
      2*n_across*n_down - (inset_top + 1)*n_across - inset_right -1,
      3),
  # top row, bottom
  seq(2*n_across*n_down - (inset_top + 4)*n_across + inset_left + 2,
      2*n_across*n_down - (inset_top + 3)*n_across - inset_right -1,
      3),
  # top row, middle
  seq(2*n_across*n_down - (inset_top + 3)*n_across + inset_left + 1,
      2*n_across*n_down - (inset_top + 2)*n_across - inset_right - 2,
      3),
  seq(2*n_across*n_down - (inset_top + 3)*n_across + inset_left + 2,
      2*n_across*n_down - (inset_top + 2)*n_across - inset_right - 1,
      3)
  
   # stars
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 103,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 103 + 500,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 103 + 1000,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 103 + 1500,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 123,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 123 + 500,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 123 + 1000,
#   c(
#       c(2762, 2762 + n_across, 2762 + 3*n_across, 2762 + 4*n_across),
#       seq(362, by = 50, length.out = 2), 
#       seq(362, by = 50, length.out = 2) + 1,
#       c(2860,2861, 2863, 2864)
#     ) + 123 + 1500
)

dark_green <- c(
  # outer every other dot
  seq((inset_bottom-1)*n_across + inset_left, 
      inset_bottom*n_across - inset_right + 1, 2),
  seq(2*n_across*n_down - inset_top*n_across + inset_left, 
      2*n_across*n_down - (inset_top - 1)*n_across - inset_right + 1, 
      2),
  seq((inset_bottom-1)*n_across + inset_left, 
      2*n_across*n_down - inset_top*n_across + inset_left, 
      2*n_across),
  seq(inset_bottom*n_across - inset_right + 1, 
      2*n_across*n_down - (inset_top - 1)*n_across - inset_right + 1, 
      2*n_across),
  # inner every other dot
  seq((inset_bottom + 5)*n_across + inset_left + 4, 
      (inset_bottom + 6)*n_across - inset_right - 3, 2),
  seq(2*n_across*n_down - (inset_top + 6)*n_across + inset_left + 4, 
      2*n_across*n_down - (inset_top + 5)*n_across - inset_right -3, 
      2),
  seq((inset_bottom + 5)*n_across + inset_left + 4, 
      2*n_across*n_down - (inset_top + 6)*n_across + inset_left + 4, 
      2*n_across),
  seq((inset_bottom + 6)*n_across - inset_right - 3, 
      2*n_across*n_down - (inset_top + 5)*n_across - inset_right -3, 
      2*n_across) 
)

hexagon <- tibble(
  x = rep(c(across_xs, across_xs + sqrt(3)/4), n_down),
  y = rep(c(across_ys, across_ys + 3/(2*sqrt(3))), n_down) + 
    rep((0:(n_down - 1))*(3/sqrt(3)), each = 2*7*n_across),
  group = rep(1:(2*n_across*n_down), each = 7),
  colors = if_else(group %in% light_green,
                   "#8aa48f",
                   if_else(group %in% dark_green,
                          "#365447",
                          "white"))
)

```

Write  a function

```{r}
make_floor_hex <- function(dim_width, dim_length, inset_left, inset_right, inset_top, inset_bottom){
  n_across <- dim_width
  n_down <- ceiling(dim_length/(3/sqrt(3)))
  
  across_xs <- rep(c(0,0, .5, 1, 1, .5, 0), n_across) +
    rep(0:(n_across-1), each = 7)
  
  across_ys <- rep(c(0, 1/sqrt(3), 3/(2*sqrt(3)), 1/sqrt(3), 0,-1/(2*sqrt(3)), 0), n_across)
  light_green <- c(
    # vertical diamonds
    # left column, middle
    seq((inset_bottom + 1)*n_across + inset_left + 2, 
        2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 2, 
        2*n_across),
    # left column, left side
    seq((inset_bottom + 2)*n_across + inset_left + 1, 
        2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 1, 
        4*n_across),
    # left column, right side
    seq((inset_bottom + 2)*n_across + inset_left + 2, 
        2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 2, 
        4*n_across),
    # right column, middle
    seq((inset_bottom + 2)*n_across - inset_right - 1, 
        2*n_across*n_down - (inset_top + 1)*n_across - inset_right -1, 
        2*n_across),
    # right column, right side
    seq((inset_bottom + 3)*n_across - inset_right - 1, 
        2*n_across*n_down - (inset_top)*n_across - inset_right - 1, 
        4*n_across),
    # right column, left side
    seq((inset_bottom + 3)*n_across - inset_right - 2, 
        2*n_across*n_down - (inset_top)*n_across - inset_right - 2, 
        4*n_across),
    # bottom row, bottom
    seq((inset_bottom + 1)*n_across + inset_left + 2,
        (inset_bottom + 2)*n_across - inset_right - 1,
        3),
    # bottom row, top
    seq((inset_bottom + 3)*n_across + inset_left + 2,
        (inset_bottom + 4)*n_across - inset_right - 1,
        3),
    # bottom row, middle
    seq((inset_bottom + 2)*n_across + inset_left + 1,
        (inset_bottom + 3)*n_across - inset_right - 2,
        3),
    seq((inset_bottom + 2)*n_across + inset_left + 2,
        (inset_bottom + 3)*n_across - inset_right - 1,
        3),
    # top row, top
    seq(2*n_across*n_down - (inset_top + 2)*n_across + inset_left + 2,
        2*n_across*n_down - (inset_top + 1)*n_across - inset_right -1,
        3),
    # top row, bottom
    seq(2*n_across*n_down - (inset_top + 4)*n_across + inset_left + 2,
        2*n_across*n_down - (inset_top + 3)*n_across - inset_right -1,
        3),
    # top row, middle
    seq(2*n_across*n_down - (inset_top + 3)*n_across + inset_left + 1,
        2*n_across*n_down - (inset_top + 2)*n_across - inset_right - 2,
        3),
    seq(2*n_across*n_down - (inset_top + 3)*n_across + inset_left + 2,
        2*n_across*n_down - (inset_top + 2)*n_across - inset_right - 1,
        3)
  )
  
  dark_green <- c(
    # outer every other dot
    seq((inset_bottom-1)*n_across + inset_left, 
        inset_bottom*n_across - inset_right + 1, 2),
    seq(2*n_across*n_down - inset_top*n_across + inset_left, 
        2*n_across*n_down - (inset_top - 1)*n_across - inset_right + 1, 
        2),
    seq((inset_bottom-1)*n_across + inset_left, 
        2*n_across*n_down - inset_top*n_across + inset_left, 
        2*n_across),
    seq(inset_bottom*n_across - inset_right + 1, 
        2*n_across*n_down - (inset_top - 1)*n_across - inset_right + 1, 
        2*n_across),
    # inner every other dot
    seq((inset_bottom + 5)*n_across + inset_left + 4, 
        (inset_bottom + 6)*n_across - inset_right - 3, 2),
    seq(2*n_across*n_down - (inset_top + 6)*n_across + inset_left + 4, 
        2*n_across*n_down - (inset_top + 5)*n_across - inset_right -3, 
        2),
    seq((inset_bottom + 5)*n_across + inset_left + 4, 
        2*n_across*n_down - (inset_top + 6)*n_across + inset_left + 4, 
        2*n_across),
    seq((inset_bottom + 6)*n_across - inset_right - 3, 
        2*n_across*n_down - (inset_top + 5)*n_across - inset_right -3, 
        2*n_across) 
  )
  
  hexagon <- tibble(
    x = rep(c(across_xs, across_xs + sqrt(3)/4), n_down),
    y = rep(c(across_ys, across_ys + 3/(2*sqrt(3))), n_down) + 
      rep((0:(n_down - 1))*(3/sqrt(3)), each = 2*7*n_across),
    group = rep(1:(2*n_across*n_down), each = 7),
    colors = if_else(group %in% light_green,
                     "#8aa48f",
                     if_else(group %in% dark_green,
                             "#365447",
                             "white"))
  )
  hexagon
}
```

Shower floor plan

```{r}
shower <- make_floor_hex(
  dim_width = 36, 
  dim_length = 72, 
  inset_left = 5, 
  inset_right = 4, 
  inset_top = 6, 
  inset_bottom = 5)
```

```{r, fig.width=10, fig.height=10}
shower %>% 
  ggplot(aes(x = x,
             y = y, 
             group = group)) +
  geom_polygon(color = "black",
               aes(fill = colors)) +
  scale_fill_identity() +
  # geom_text(data = . %>%
  #             group_by(group) %>%
  #             summarize(mid_x = mean(x),
  #                       mid_y = mean(y)),
  #           aes(x = mid_x,
  #               y = mid_y,
  #               label = group)) +
  coord_equal() +
  theme_void()
```


The rest of the bathroom

```{r}
bathroom <- make_floor_hex(
  dim_width = 111, 
  dim_length = 77.875, 
  inset_left = 6, 
  inset_right = 18, 
  inset_top = 4, 
  inset_bottom = 5)
```

Weird corner

```{r}
corner <- make_floor_hex(
  dim_width = 41,
  dim_length = 34,
  inset_left = 1,
  inset_right = 1,
  inset_top = 2,
  inset_bottom = 5
)
```


Now figure out how to put them together ... got it! Not perfect but good enough. Clean up the corner stuff manually later.

```{r, fig.width=10, fig.height=10}
floor_distance <- 36 # should make this a parameter ... but too lazy right now

bathroom %>% 
 mutate(x = x + floor_distance) %>% 
  ggplot() +
  geom_polygon(color = "black",
               aes(x = x,
                   y = y, 
                   group = group,
                   fill = colors)) +
  geom_polygon(data = shower,
               color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = corner %>% mutate(x = x + floor_distance + 53),
               color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = corner %>% 
                 mutate(x = x + floor_distance + 53)  %>% 
                 filter(group %in% c(247, 329, 292:296, 252:255, 334:337, 171, 417,
                                     1267:1271, 1309, 1310)),
               fill = "white",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = corner %>% 
                 mutate(x = x + floor_distance + 53)  %>% 
                 filter(group %in% c(251, 333, 1351)),
               fill = "#365447",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = corner %>% 
                 mutate(x = x + floor_distance + 53)  %>% 
                 filter(group %in% c(1597, 1637, 1638)),
               fill = "#8aa48f",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = tibble(x = c(61, 61, 111.5, 111.5, 61) +
                               floor_distance,
                             y = c(-.5, 25 + 5/8, 25 + 5/8, -.5, -.5)),
               aes(x = x,
                   y = y),
               fill = "white") +
  # geom_polygon(data = tibble(x = c(31, 31, 61, 61, 31) + floor_distance,
  #                            y = c(-.5, 21, 21, -.5, -.5)),
  #              aes(x = x,
  #                  y = y),
  #              fill = "#8aa48f") +
  geom_polygon(data = tibble(x = c(99, 99, 111.5, 111.5, 99) + floor_distance,
                             y = c(25 + 5/8, 78, 78, 25 + 5/8, 25 + 5/8)),
               aes(x = x,
                   y = y),
               fill = "#8aa48f") +
  geom_segment(data = tibble(x = 36, y = 0, xend = 36, yend = 72.5),
               aes(x = x, y = y, xend = xend, yend = yend),
               size = 2) +
  # geom_ellipse(data = tibble(x0 = 15.5 + floor_distance,
  #                  y0 = 11.5,
  #                  a = 8.25, b = 11.5, angle = 0),
  #              aes(x0 = x0, y0 = y0, a = a, b = b, angle = angle),
  #              fill = "white",
  #              color = "black",
  #              size = 2) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```

Trying patterns on big floor plan

```{r, fig.width=10, fig.height=10}
floor_distance <- 36 # should make this a parameter ... but too lazy right now

lg_base <- c(
        #1486, 1487, 1451, 1523,
        1488,
        1494, 1495, 1459, 1531,
        #1502, 1503,1467, 1539,
        1501,
        1099, 1170, 1172, 
        1818, 1820, 1891,
        1526, 1599, 1672, 1745,
        1454, 1383, 1312, 1241,
        1749, 1678, 1607, 1536,
        1245, 1318, 1391, 1464,
        955, 990, 991, 1027,
        1963, 1998, 1999, 2035) 

lg_up <- lg_base + 14*36

lg_down <- lg_base - 14*36

dg_base <- c(
        1488,1487, 1452, 1524,
        1494, 1495, 1459, 1531,
        #1502, 1503,1467, 1539,
        1501, 1502, 1466, 1538,
        955, 990, 991, 1027,
        1963, 1998, 1999, 2035
)

dg_up <- dg_base + 14*36

dg_down <- dg_base - 14*36


bathroom %>% 
 mutate(x = x + floor_distance) %>% 
  ggplot() +
  geom_polygon(color = "black",
               aes(x = x,
                   y = y, 
                   group = group,
                   fill = colors)) +
  geom_polygon(data = shower,
               color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = shower %>% 
                 filter(group %in% lg_up),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#8aa48f",
               color = "black") +
  geom_polygon(data = shower %>% 
                 filter(group %in% lg_down),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#8aa48f",
               color = "black") +
  geom_polygon(data = shower %>% 
                 filter(group %in% dg_up),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#365447",
               color = "black") +
  geom_polygon(data = shower %>% 
                 filter(group %in% dg_down),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#365447",
               color = "black") +
  geom_polygon(data = corner %>% mutate(x = x + floor_distance + 53),
               color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = corner %>% 
                 mutate(x = x + floor_distance + 53)  %>% 
                 filter(group %in% c(247, 329, 292:296, 252:255, 334:337, 171, 417,
                                     1267:1271, 1309, 1310)),
               fill = "white",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = corner %>% 
                 mutate(x = x + floor_distance + 53)  %>% 
                 filter(group %in% c(251, 333, 1351)),
               fill = "#365447",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = corner %>% 
                 mutate(x = x + floor_distance + 53)  %>% 
                 filter(group %in% c(1597, 1637, 1638)),
               fill = "#8aa48f",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = tibble(x = c(61, 61, 111.5, 111.5, 61) +
                               floor_distance,
                             y = c(-.5, 25 + 5/8, 25 + 5/8, -.5, -.5)),
               aes(x = x,
                   y = y),
               fill = "white") +
  # geom_polygon(data = tibble(x = c(31, 31, 61, 61, 31) + floor_distance,
  #                            y = c(-.5, 21, 21, -.5, -.5)),
  #              aes(x = x,
  #                  y = y),
  #              fill = "#8aa48f") +
  geom_polygon(data = tibble(x = c(99, 99, 111.5, 111.5, 99) + floor_distance,
                             y = c(25 + 5/8, 78, 78, 25 + 5/8, 25 + 5/8)),
               aes(x = x,
                   y = y),
               fill = "#8aa48f") +
  geom_segment(data = tibble(x = 36, y = 0, xend = 36, yend = 72.5),
               aes(x = x, y = y, xend = xend, yend = yend),
               size = 2) +
  # geom_ellipse(data = tibble(x0 = 15.5 + floor_distance,
  #                  y0 = 11.5,
  #                  a = 8.25, b = 11.5, angle = 0),
  #              aes(x0 = x0, y0 = y0, a = a, b = b, angle = angle),
  #              fill = "white",
  #              color = "black",
  #              size = 2) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```


Trying patterns in their small spaces and experimenting.

```{r, fig.width=5, fig.height=10}
shower %>% 
  ggplot() +
  geom_polygon(color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = . %>% 
                 filter(group %in% c(1486, 1487, 1489, 1492,
                                     1451, 1523,
                                     1494, 1495, 1459, 1531,
                                     1497, 1500, 1502, 1503, 
                                     1467, 1539,
                                     1099, 1170, 1172, 1134, 1135,
                                     1818, 1820, 1854, 1855, 1891,
                                     1529, 1565, 1602, 1638, 1675,
                                     1639, 1604, 1568, 1533,
                                     1457, 1421, 1386, 1350, 1315,
                                     1351, 1388, 1424, 1461,
                                     1526, 1562, 1599, 1635, 1672, 1708, 1745, 1781,
                                     1454, 1418, 1383, 1347, 1312, 1276, 1241, 1205,
                                     1784, 1749, 1713, 1678, 1642, 1607, 1571, 1536,
                                     1281, 1245, 1208, 1318, 1354, 1391, 1427, 1464)),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#8aa48f",
               color = "black") +
  geom_text(data = . %>%
              group_by(group) %>%
              summarize(mid_x = mean(x),
                        mid_y = mean(y)),
            aes(x = mid_x,
                y = mid_y,
                label = group)) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```


Favorite shower pattern so far:

```{r, fig.width=5, fig.height=10}
lg_base <- c(
        #1486, 1487, 1451, 1523,
        1488,
        1494, 1495, 1459, 1531,
        #1502, 1503,1467, 1539,
        1501,
        1099, 1170, 1172, 
        1818, 1820, 1891,
        1526, 1599, 1672, 1745,
        1454, 1383, 1312, 1241,
        1749, 1678, 1607, 1536,
        1245, 1318, 1391, 1464,
        955, 990, 991, 1027,
        1963, 1998, 1999, 2035) 

lg_up <- lg_base + 14*36

lg_down <- lg_base - 14*36

dg_base <- c(
        1488,1487, 1452, 1524,
        1494, 1495, 1459, 1531,
        #1502, 1503,1467, 1539,
        1501, 1502, 1466, 1538,
        955, 990, 991, 1027,
        1963, 1998, 1999, 2035
)

dg_up <- dg_base + 14*36

dg_down <- dg_base - 14*36


shower %>% 
  ggplot() +
  geom_polygon(color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = . %>% 
                 filter(group %in% lg_up),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#8aa48f",
               color = "black") +
  geom_polygon(data = . %>% 
                 filter(group %in% lg_down),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#8aa48f",
               color = "black") +
  geom_polygon(data = . %>% 
                 filter(group %in% dg_up),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#365447",
               color = "black") +
  geom_polygon(data = . %>% 
                 filter(group %in% dg_down),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#365447",
               color = "black") +
  # geom_text(data = . %>%
  #             group_by(group) %>%
  #             summarize(mid_x = mean(x),
  #                       mid_y = mean(y)),
  #           aes(x = mid_x,
  #               y = mid_y,
  #               label = group)) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```


```{r, fig.width=5, fig.height=10}
shower %>% 
  ggplot() +
  geom_polygon(color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group)) +
  geom_polygon(data = . %>% 
                 filter(group %in% c(1891, 1854:1855, 1818:1820,
                                     1781:1784, 1745:1749, 1708:1713, 
                                     1672:1678, 1635:1642, 1599:1607,
                                     1562:1571, 1526:1536, 1489:1500,
                                     1454:1464, 1418:1427, 1383:1391, 
                                     1347:1354, 1312:1318, 1276:1281, 
                                     1241:1245, 1205:1208, 1170:1172, 
                                     1134:1135, 1099,
                                     1486, 1487, 1451, 1523,
                                     1502, 1503, 1467, 1539
                                     
                                     )),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#8aa48f",
               color = "black") +
  geom_polygon(data = . %>% 
                 filter(group %in% c(1603, 1566:1567, 1530:1532,
                                     1493:1496, 1458:1460, 1422:1423,
                                     1387,
                                     883, 918, 919, 955
                                     )),
               aes(x = x,
                   y = y,
                   group = group),
               fill = "#365447",
               color = "black") +
  geom_text(data = . %>%
              group_by(group) %>%
              summarize(mid_x = mean(x),
                        mid_y = mean(y)),
            aes(x = mid_x,
                y = mid_y,
                label = group)) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```

```{r, fig.width=6, fig.height=5}
corner %>% 
  ggplot() +
  geom_polygon(color = "black",
               aes(x = x,
                   y = y, 
                   fill = colors, 
                   group = group))  +
  geom_polygon(data = corner %>% 
                 filter(group %in% c(247, 329, 292:296, 252:255, 334:337, 171, 417,
                                     1267:1271, 1309, 1310)),
               fill = "white",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = corner %>% 
                 filter(group %in% c(251, 333, 1351)),
               fill = "#365447",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_polygon(data = corner %>% 
                 filter(group %in% c(1597, 1637, 1638)),
               fill = "#8aa48f",
               color = "black",
               aes(x = x,
                   y = y,
                   group = group)) +
  geom_text(data = . %>%
              group_by(group) %>%
              summarize(mid_x = mean(x),
                        mid_y = mean(y)),
            aes(x = mid_x,
                y = mid_y,
                label = group)) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```





```{r, fig.width=10, fig.height=10}

# #8aa48f light
# #365447 dark
# #754a41 burgundy

hexagon %>% 
  ggplot(aes(x = x,
             y = y, 
             group = group)) +
  geom_polygon(color = "black",
               aes(fill = colors)) +
  geom_polygon(data = hexagon2,
               aes(fill = colors),
               color = "black") +
  geom_text(data = . %>%
              group_by(group) %>%
              summarize(mid_x = mean(x),
                        mid_y = mean(y)),
            aes(x = mid_x,
                y = mid_y,
                label = group)) +
  geom_text(data = hexagon2 %>%
              group_by(group) %>%
              summarize(mid_x = mean(x),
                        mid_y = mean(y)),
            aes(x = mid_x,
                y = mid_y,
                label = group)) +
  scale_fill_identity() +
  coord_equal() +
  theme_void()
```

```{r}
ggsave(filename = "bathroom_floor.png")
ggsave(filename = "bathroom_floor.pdf")

ggsave(filename = "bathroom_floor_numbered.pdf", height = 40, width = 30)
```

